package com.github.angel.raa.modules.utils.enums;

public enum PermissionEnum {
    READ_ALL_PRODUCTS,
    READ_ONE_PRODUCT,
    CREATE_ONE_PRODUCT,
    UPDATE_ONE_PRODUCT,
    DELETE_ONE_PRODUCT,
    DISABLE_ONE_PRODUCT,

    READ_ALL_CATEGORIES,
    READ_ONE_CATEGORIES,
    CREATE_ONE_CATEGORIES,
    UPDATE_ONE_CATEGORIES,
    DELETE_ONE_CATEGORIES,
    DISABLE_ONE_CATEGORIES,


    READ_MY_PROFILE;



}
